const products = [
  {
    product_id: '11111111-1111-1111-1111-111111111111',
    name: 'Slim Fit Jeans',
    description: 'Classic slim fit jeans with stretch fabric.',
    brand: "levis",
    category_paths: ['men/clothing/jeans'],
    tags: ['stretch', 'premium'],
    min_price: 59.99,
    max_price: 79.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.5,
    is_sponsored: false,
    merch_priority: 2,
    price_bucket: 'mid',
    sale_price: 49.99,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: false,
    pinned_rank: null,
    is_featured: true
  },
  {
    product_id: '22222222-2222-2222-2222-222222222222',
    name: 'AirFlex Jogger',
    description: 'Tapered jogger with breathable four-way stretch fabric.',
    brand: 'nike',
    category_paths: ['apparel/mens/bottoms'],
    tags: ['athleisure', 'stretch', 'travel'],
    min_price: 69.99,
    max_price: 89.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.7,
    is_sponsored: true,
    merch_priority: 1,
    price_bucket: 'mid',
    sale_price: null,
    sale_start: null,
    sale_end: null,
    is_pinned: true,
    pinned_rank: 1,
    is_featured: false
  },
  {
    product_id: '33333333-3333-3333-3333-333333333333',
    name: 'TrailLite Sneaker',
    description: 'Lightweight trail runner with Vibram outsole.',
    brand: 'nike',
    category_paths: ['footwear/outdoors/mens'],
    tags: ['trail', 'water-resistant', 'vibram'],
    min_price: 120.00,
    max_price: 140.00,
    embedding: null,
    in_stock: false,
    updated_at: new Date(),
    rating: 4.2,
    is_sponsored: false,
    merch_priority: 3,
    price_bucket: 'high',
    sale_price: 110.00,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: false,
    pinned_rank: null,
    is_featured: false
  },
  {
    product_id: '44444444-4444-4444-4444-444444444444',
    name: 'Classic Chinos',
    description: 'Versatile chinos for work or weekend.',
    brand: 'puma',
    category_paths: ['men/clothing/pants'],
    tags: ['versatile', 'work', 'weekend'],
    min_price: 49.99,
    max_price: 69.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.0,
    is_sponsored: false,
    merch_priority: 4,
    price_bucket: 'low',
    sale_price: null,
    sale_start: null,
    sale_end: null,
    is_pinned: false,
    pinned_rank: null,
    is_featured: false
  },
  {
    product_id: '55555555-5555-5555-5555-555555555555',
    name: 'Denim Jacket',
    description: 'Iconic denim jacket with modern fit.',
    brand: "levis",
    category_paths: ['men/clothing/jackets'],
    tags: ['denim', 'iconic', 'modern'],
    min_price: 89.99,
    max_price: 109.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.8,
    is_sponsored: true,
    merch_priority: 1,
    price_bucket: 'high',
    sale_price: 79.99,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: true,
    pinned_rank: 2,
    is_featured: true
  },
  {
    product_id: '66666666-6666-6666-6666-666666666666',
    name: 'Performance T-Shirt',
    description: 'Moisture-wicking t-shirt for active wear.',
    brand: 'adidas',
    category_paths: ['men/clothing/tshirts'],
    tags: ['performance', 'active', 'moisture-wicking'],
    min_price: 29.99,
    max_price: 39.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.3,
    is_sponsored: false,
    merch_priority: 2,
    price_bucket: 'low',
    sale_price: 24.99,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: false,
    pinned_rank: null,
    is_featured: false
  },
  {
    product_id: '77777777-7777-7777-7777-777777777777',
    name: 'Yoga Leggings',
    description: 'High-waisted leggings for yoga and fitness.',
    brand: 'reebok',
    category_paths: ['women/clothing/leggings'],
    tags: ['yoga', 'fitness', 'high-waisted'],
    min_price: 49.99,
    max_price: 59.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.6,
    is_sponsored: false,
    merch_priority: 3,
    price_bucket: 'mid',
    sale_price: null,
    sale_start: null,
    sale_end: null,
    is_pinned: false,
    pinned_rank: null,
    is_featured: true
  },
  {
    product_id: '88888888-8888-8888-8888-888888888888',
    name: 'Running Shorts',
    description: 'Lightweight shorts for running and training.',
    brand: 'adidas',
    category_paths: ['men/clothing/shorts'],
    tags: ['running', 'lightweight', 'training'],
    min_price: 34.99,
    max_price: 44.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.1,
    is_sponsored: false,
    merch_priority: 2,
    price_bucket: 'low',
    sale_price: 29.99,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: false,
    pinned_rank: null,
    is_featured: false
  },
  {
    product_id: '99999999-9999-9999-9999-999999999999',
    name: 'Winter Parka',
    description: 'Insulated parka for cold weather.',
    brand: 'northface',
    category_paths: ['men/clothing/jackets'],
    tags: ['winter', 'insulated', 'parka'],
    min_price: 149.99,
    max_price: 179.99,
    embedding: null,
    in_stock: false,
    updated_at: new Date(),
    rating: 4.9,
    is_sponsored: true,
    merch_priority: 5,
    price_bucket: 'high',
    sale_price: 139.99,
    sale_start: new Date(Date.now() - 86400000),
    sale_end: new Date(Date.now() + 86400000),
    is_pinned: false,
    pinned_rank: null,
    is_featured: true
  },
  {
    product_id: '10101010-1010-1010-1010-101010101010',
    name: 'Graphic Tee',
    description: 'Cotton t-shirt with bold graphic print.',
    brand: 'puma',
    category_paths: ['men/clothing/tshirts'],
    tags: ['cotton', 'graphic', 'print'],
    min_price: 19.99,
    max_price: 29.99,
    embedding: null,
    in_stock: true,
    updated_at: new Date(),
    rating: 4.0,
    is_sponsored: false,
    merch_priority: 1,
    price_bucket: 'low',
    sale_price: null,
    sale_start: null,
    sale_end: null,
    is_pinned: false,
    pinned_rank: null,
    is_featured: false
  }
];

export default products;